config/routes.rb
Rails.application.routes.draw do

  get 'all_setting' => 'project#all_setting'
  get 'index' => 'project#index'
  get 'calender_and_task' => 'project#calender_and_task'
  get 'profile' => 'project#profile'
  get 'case_page' => 'project#case_page'
  get 'completed_task' => 'project#completed_task'
  get 'list_category' => 'project#list_category'
  get 'setting_page' => 'project#setting_page'

  get 'close_opportunity' => 'project#close_opportunity'

  get 'add_status' => 'project#add_status'
  get 'list_status' => 'project#list_status'

  get 'add_milestone' => 'project#add_milestone'
  get 'list_milestone' => 'project#list_milestone'

  get 'oraganization_profile' => 'project#oraganization_profile'
  post 'oraganization_profile' => 'project#oraganization_profile'

  get 'person_profile' => 'project#person_profile'
  post 'person_profile' => 'project#person_profile'
  
  get 'list_organization' => 'project#list_organization'
  post 'list_organization' => 'project#list_organization'

  get 'list_person' => 'project#list_person'
  post 'list_person' => 'project#list_person'
  
  get 'list_cases' => 'project#list_cases'
  post 'list_cases' => 'project#list_cases'
  
  get 'case_details' => 'project#case_details'
  
  get 'list_opportunity' => 'project#list_opportunity'
  post 'list_opportunity' => 'project#list_opportunity'
  
  get 'opportunity_details' => 'project#opportunity_details'
  get 'list_track' => 'project#list_track'
  post 'list_track' => 'project#list_track'

  get 'list_priority' => 'project#list_priority'
  post 'list_priority' => 'project#list_priority'
  
  get 'list_task_category' => 'project#list_task_category'
  post 'list_task_category' => 'project#list_task_category'

  get 'list_notes' => 'project#list_notes'
  post 'list_notes' => 'project#list_notes'

  get 'add_opportunity' => 'project#add_opportunity'
  post 'add_opportunity' => 'project#add_opportunity'
  
  get 'all_task' => 'project#all_task'
  post 'all_task' => 'project#all_task'
  
  get 'add_organization' => 'project#add_organization'
  get 'add_person' => 'project#add_person'
  get 'all_members' => 'project#all_members'
  get 'add_track' => 'project#add_track'
  get 'add_task_category' => 'project#add_task_category'
  get 'add_task' => 'project#add_task'
  get 'add_note' => 'project#add_note'
  get 'add_opportunity' => 'project#add_opportunity'
  get 'add_priority' => 'project#add_priority'
  post 'add_priority' => 'project#add_priority'
  get 'add_case' => 'project#add_case'
  post 'add_case' => 'project#add_case'

  get 'sales_pipeline' => 'project#sales_pipeline'
  

  root 'project#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  
  def index
  end

  def calender_and_task
  end

  def profile
  end

  def case_page
  end
  
  def completed_task
  end

  def list_category
  end

  def list_cases
  end

  def case_details
  end

  def list_opportunity
  end
  
  def opportunity_details
  end

  def list_track
  end

  def list_priority
  end

  def list_task_category
  end

  def add_opportunity
  end

  def all_task
  end

  def add_organization
  end

  def add_person
  end
  
  def all_members
  end

  def add_track
  end

  def add_task_category
  end

  def add_task
  end

  def add_note
  end

  def add_opportunity
  end

  def add_priority
  end

  def add_case
  end
  
  def list_notes
  end

  def oraganization_profile
  end

  def setting_page
  end

  def add_milestone
  end

  def list_miltestone
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
  <title>NewProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'main_header' %>
</head>
<body>
	<%= render 'side_bar' %>
	<%= render 'page_header' %>
	<div class="content">
		<%= yield %>
	</div>
</body>
</html>

app/views/project/_all_setting.html.erb
<body class="pace-done sidebar-xs">
	<div class="sidebar sidebar-secondary sidebar-default">
		<div class="sidebar-content">
			<div class="sidebar-category">
				<div class="category-title">
					<span>Setting Panel</span>
					<ul class="icons-list">
						<li><a href="#" data-action="collapse"></a></li>
					</ul>
				</div>

				<div class="category-content">
					<div class="row">
						<div class="col-xs-6">
							<a href="list_track">
								<button class="btn bg-teal-400 btn-block btn-float btn-float-lg" type="button">
								<i class="glyphicon glyphicon-road"></i>
								<span>Track</span>
							</button>
							</a><br/>
							<a href="list_cases">
								<button class="btn bg-purple-300 btn-block btn-float btn-float-lg" type="button">
									<i class=" icon-books"></i> <span>Case</span>
								</button>
							</a><br/>
							<a href="list_milestone">
								<button class="btn bg-success-600 btn-block btn-float btn-float-lg" type="button">
									<i class="icon-meter-slow"></i> <span>Milestone</span>
								</button>
							</a>
						</div>
						<div class="col-xs-6">
							<a href="list_priority">
								<button class="btn bg-warning-400 btn-block btn-float btn-float-lg" type="button">
									<i class="icon-warning22"></i> <span>Priority</span>
								</button>
							</a><br/>
							<a href="list_status">
								<button class="btn bg-blue btn-block btn-float btn-float-lg" type="button">
									<i class="icon-pulse2"></i> <span>Status</span>
								</button>
							</a><br/>
							<a href="list_category">
								<button class="btn bg-orange btn-block btn-float btn-float-lg" type="button">
									<i class="icon-pulse2"></i> <span>Category</span>
								</button>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>

app/views/project/add_case.html.erb
<%= content_for :header do %>
	Setting - List Cases - Add Case
<% end %>
<%= content_for :Listheader do %>
	<li><a href="#">Setting</a></li>
	<li><a href="list_cases">List Cases</a></li>
	<li class="active">Add Case</li>
<% end %>
<div class="row">
	<div class="col-lg-3 col-md-3">
		<%= render 'all_setting' %>
	</div>
	<div class="col-lg-9 col-md-9">
		<div class="panel panel-flat">
			<div class="panel-heading">
				<span class="my-heading">Add Case</span>
				<%=link_to 'Listing page' , list_cases_path , class:" icon-arrow-left15 pull-right"%>
			</div>
			<%= form_tag({:controller => "project", :action => "list_cases"}, :class=> "form-horizontal form-validate-jquery" )do %>
				<div class="panel-body">
					<div class="form-group">
						<div class="row">
							<div class="co-lg-8 col-md-8">
								<label>Case Name  </label>
								<%= text_field_tag 'case_name' , nil , class: 'form-control' , :required => true %>
							</div>
						</div>
					</div>
					<div class="form-group">
						<div class="row">
							<div class="co-lg-8 col-md-8">
								<label>Case Details  </label>
								<%= text_area_tag 'case_details' , nil , class: 'form-control' , :required => true %>
							</div>
						</div>
					</div>
					<div class="form-group">
						<div class="row">
							<div class="co-lg-8 col-md-8">
								<label>Related to  </label>
								<select data-placeholder="Select a Opportunity" class="select" required = true>
									<option>
										<optgroup label="Opportunities">
											<option>BMS</option>
											<option>Mobi-print</option>
											<option>PGP</option>
											<option>Stadium</option>
										</optgroup>
									</option>
								</select>
							</div>
						</div>
					</div>
					<div class="form-group">
						<div class="row">
							<div class="co-lg-8 col-md-8">
								<label>Reported to  </label>
								<%= text_field_tag 'emp' , nil , class: "form-control" , value: "Karan Vyas" , :disabled => true %>
							</div>
						</div>
					</div>
					<div class="form-group" id="note_text">
						<div class="row">
							<div class="co-lg-8 col-md-8">
								<label>Note  </label>
								<%= text_area_tag 'note' , nil , class: "form-control" , :required => true %>
							</div>
						</div>
					</div>
					<div class="form-group">
						<div class="row">
							<div class="co-lg-8 col-md-8">
								<%= button_to 'Save' , nil , class: 'btn btn-primary' %>
							</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/project/add_note.html.erb
<%= content_for :header do %>
	Add Note
<% end %>
<div class="panel panel-default">
	<div class="panel-heading">
		<span class="my-heading">Note</span>
	</div>
	<div class="panel-body">
		<%= form_tag({:controller => "project", :action => "list_notes"}, :class=> "form-horizontal form-validate-jquery" )do %>
			<div class="form-group">
				<div class="row">
					<div class="col-lg-8 col-md-8">
						<label>Employee  </label>
						<%= text_field_tag 'emp' , nil , class: "form-control" , :disabled => true , :value => "Dhaval Trivedi" %>
					</div>
				</div>
			</div>
			<div class="form-group">
				<div class="row">
					<div class="col-lg-8 col-md-8">
						<label>Subject  </label>
						<%= text_field_tag 'subject' , nil , class: "form-control", :required => true %>
					</div>
				</div>
			</div>
			<div class="form-group">
				<div class="row">
					<div class="col-lg-8 col-md-8">
						<label> Related to </label>
						<select data-placeholder="Select a Opportunity" class="select" required = true>
							<option>
								<optgroup label="Categories">
									<option>Organization</option>
									<option>Opportunity</option>
									<option>Person</option>
								</optgroup>
							</option>
						</select>
					</div>
				</div>
			</div>
			<div class="form-group">
				<div class="row">
					<div class="col-lg-8 col-md-8">
						<label>Details  </label>
						<%= text_area_tag 'details' , nil , class: "form-control", :required => true %>
					</div>
				</div>
			</div>
			<div class="form-group">
				<div class="row">
					<div class="col-lg-8 col-md-8">
						<%= button_to 'Save' , case_page_path , class: "btn btn-primary" %>
						<%= link_to 'Cancle' , case_page_path , class: "btn btn-link" %>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/project/add_opportunity.html.erb
<%= content_for :header do %>
	List Opportunity - Add Opportunity
<% end %>
<%= content_for :Listheader do %>
	<li><a href="list_opportunity">List Opportunity</a></li>
	<li class="active">Add Opportunity</li>
<% end %>
<div class="panel panel-default">
	<div class="panel-heading">
		<div class="my-heading">Opportunity</div>
	</div>
	<%= form_tag({:controller => "project", :action => "list_opportunity"}, :class=> "form-horizontal form-validate-jquery" )do %>
		<div class="panel-body">
			<div class="form-group">
				<div class="row">
					<div class="col-lg-7 col-md-7">
						<label> Client  </label>
						<select data-placeholder = "Select Client" class="select-search" required = true>
	                        <option>
		                        <optgroup>
			                        <option value="opt2">Nikhil Patel</option>
			                        <option value="opt3">Infosys</option>
			                        <option value="opt4">Streebo solutions</option>
			                        <option value="opt5">NetSqure Pvt ltd.</option>
			                        <option value="opt6">USA Gov</option>
		                        </optgroup>
	                        </option>
	                    </select>
					</div>
				</div>
			</div>
			<div class="form-group">
				<div class="row">
					<div class="col-lg-7 col-md-7">
						<label> Opportunity Name  </label>
						<%= text_field_tag 'opp_name' , nil , class: "form-control" , :required => true %>
					</div>
				</div>
			</div>
			<div class="form-group">
				<div class="row">
					<div class="col-lg-7 col-md-7">
						<label> Details  </label>
						<%= text_area_tag 'opp_details' , nil , class: "form-control" , :required => true%>
					</div>
				</div>
			</div>
			<div class="form-group">
				<div class="row">
					<div class="col-lg-12 col-md-12">
						<label> Expacted Value  </label>
						<div class="row">
							<div class="col-lg-2 col-md-2">
			                        <%= text_field_tag '' , nil , class: "form-control",  value: "INR - Rs" , :disabled => true%>
			                </div>
			                <div class="col-lg-2 col-md-2">
			                    <%= text_field_tag 'exp_value' , nil , class: "form-control",  placeholder: "Value" , :required => true %>
			                </div>
			                <div class="col-lg-2 col-md-2">
			                    <select class="select" id="price_format">
			                    	<option value="fixed">fixed</option>
			                    	<option value="per_hour">per hour</option>
			                    	<option value="per_day">per day</option>
			                    	<option value="per_month">per month</option>
			                    	<option value="per_year">per year</option>
			                    </select>
			                </div>
			                <div class="col-lg-2 col-md-2" style="display:none" id="per_hour_text">
			                	<div class="row">
			                		<div class="col-lg-2 col-md-2">
			                			for
			                		</div>
			                		<div class="col-lg-8 col-md-8">
			                     		<%= text_field_tag 'hour' , nil , class: "form-control",  placeholder: "Value" %>
			                     	</div>
			                     	<div class="col-lg-2 col-md-2">
			                     		hour
			                     	</div>
			                    </div>
			                </div>
			                <div class="col-lg-2 col-md-2" style="display:none" id="per_day_text">
			                	<div class="row">
			                		<div class="col-lg-2 col-md-2">
			                			for
			                		</div>
			                		<div class="col-lg-8 col-md-8">
			                     		<%= text_field_tag 'day' , nil , class: "form-control",  placeholder: "Value" %>
			                     	</div>
			                     	<div class="col-lg-2 col-md-2">
			                     		day
			                     	</div>
			                    </div>
			                </div>
			                <div class="col-lg-2 col-md-2" style="display:none" id="per_month_text">
			                	<div class="row">
			                		<div class="col-lg-2 col-md-2">
			                			for
			                		</div>
			                		<div class="col-lg-8 col-md-8">
			                     		<%= text_field_tag 'month' , nil , class: "form-control",  placeholder: "Value" %>
			                     	</div>
			                     	<div class="col-lg-2 col-md-2">
			                     		month
			                     	</div>
			                    </div>
			                </div>
			                <div class="col-lg-2 col-md-2" style="display:none" id="per_year_text">
			                	<div class="row">
			                		<div class="col-lg-2 col-md-2">
			                			for
			                		</div>
			                		<div class="col-lg-8 col-md-8">
			                     		<%= text_field_tag 'year' , nil , class: "form-control",  placeholder: "Value" %>
			                     	</div>
			                     	<div class="col-lg-2 col-md-2">
			                     		year
			                     	</div>
			                    </div>
			                </div>

			                
			            </div>
					</div>
				</div>
			</div>
			<div class="form-group">
				<div class="row">
					<div class="col-lg-2 col-md-2">
						<label>Milestone </label>
	                    <select data-placeholder = "Select Milestone" class="select" required = true id="milestone">
	                    	<option>
	                    		<optgroup>
			                    	<option value="new">New</option>
			                    	<option value="analysis">Analysis</option>
			                    	<option value="desinging">Desinging</option>
			                    	<option value="negotiation">Negotiation</option>
			                    	<option value="bid">Bid</option>
			                    	<option value="lost">Lost</option>
			                    	<option value="won">Won</option>
		                    	</optgroup>
	                    	</option>
	                    </select>
	                </div>
	                <div class="col-lg-3 col-md-3">
	                	<label> Probability of Winning(%) </label>
	             		<%= text_field_tag 'prob_win' , nil , id:"milestone_per", class: "form-control" , :disabled => true%>
	                </div>

				</div>
			</div>
			<div class="form-group">
				<div class="row">
					<div class="col-lg-7 col-md-7">
						<label> Expacted Colse Date  </label>
						<div class="input-group">
							<span class="input-group-addon"><i class="icon-calendar5"></i></span>
							<%= text_field_tag 'close_date' , nil , class: "form-control pickadate" , :required => true %>
						</div>
						
					</div>
				</div>
			</div>
			<div class="form-group">
				<div class="row">
					<div class="col-lg-7 col-md-7">
						<label> Track </label>
						<select data-placeholder = "Select Track" class="select" required = true>
							<option>
								<optgroup>
			                    	<option value="select">Select</option>
			                    	<option value="new">BMS</option>
			                    	<option value="analysis">Hospital Management</option>
			                    	<option value="desinging">Mobi print</option>
			                    	<option value="negotiation">PGP</option>
		                    	</optgroup>
	                    	</option>
	                    </select>
					</div>
				</div>
			</div>
			<div class="form-group">
				<div class="row">
					<div class="col-lg-7 col-md-7">
						<label> Assigned To </label>
						<select data-placeholder="Select Employee" class="select" required = true>
	                    	<option>
	                    		<optgroup>
			                    	<option value="new">Karan Vyas</option>
			                    	<option value="analysis">Krishna Mehta</option>
			                    	<option value="desinging">Mayur Shah</option>
			                    	<option value="negotiation">Sanjay Vizuda</option>
			                    </optgroup>
	                    	</option>
	                    </select>
					</div>
				</div>
			</div>
			<div class="form-group">
				<div class="row">
					<div class="col-lg-7 col-md-7">
						<div>
							<%= submit_tag 'Save', class: 'btn btn-primary' %>
							<%= link_to 'Cancel' , list_opportunity_path , class: 'btn btn-link' %>
						</div>
					</div>
				</div>
			</div>
		</div>
	<% end %>
</div>
<script type="text/javascript">
	$("#price_format").on('change', function(){
		if(this.value == "per_hour")
		{
			$('#per_hour_text').show();
			$('#per_day_text').hide();
			$('#per_month_text').hide();
			$('#per_year_text').hide();
		}
		else if(this.value == "per_day")
		{
			$('#per_day_text').show();
			$('#per_hour_text').hide();
			$('#per_month_text').hide();
			$('#per_year_text').hide();
		}
		else if(this.value == "per_month")
		{
			$('#per_month_text').show();
			$('#per_hour_text').hide();
			$('#per_day_text').hide();
			$('#per_year_text').hide();
		}
		else if(this.value == "per_year")
		{
			$('#per_year_text').show();
			$('#per_hour_text').hide();
			$('#per_day_text').hide();
			$('#per_month_text').hide();
		}
		else if(this.value == "fixed")
		{
			$('#per_hour_text').hide();
			$('#per_day_text').hide();
			$('#per_month_text').hide();
			$('#per_year_text').hide();
		}
	});

	$("#milestone").on('change', function(){
		if(this.value == "new")
		{
			document.getElementById("milestone_per").value = "10%";
		}
		else if(this.value == "analysis")
		{
			document.getElementById("milestone_per").value = "25%";
		}
		else if(this.value == "desinging")
		{
			document.getElementById("milestone_per").value = "50%";
		}
		else if(this.value == "negotiation")
		{
			document.getElementById("milestone_per").value = "80%";
		}
		else if(this.value == "bid")
		{
			document.getElementById("milestone_per").value = "70%";
		}
		else if(this.value == "lost")
		{
			document.getElementById("milestone_per").value = "0%";
		}
		else if(this.value == "won")
		{
			document.getElementById("milestone_per").value = "100%";
		}
		else
		{
			document.getElementById("milestone_per").value = " ";
		}
	});
</script>
	

app/views/project/add_task_category.html.erb
<%= content_for :header do %>
	Setting - List Category - Add Category
<% end %>
<%= content_for :Listheader do %>
	<li>Setting</li>
	<li>List Category</li>
	<li class="active">Add Category</li>
<% end %>
<div class="row">
	<div class="col-lg-3 col-md-3">
		<%= render 'all_setting' %>
	</div>
	<div class="col-lg-9 col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				<span class="my-heading">Task Category</span>
				<%= link_to ' ' , list_task_category_path , class: "glyphicon glyphicon-arrow-left pull-right" %>
			</div>
			<div class="panel-body">
				<%= form_tag({:controller => "project", :action => "list_task_category"}, :class=> "form-horizontal form-validate-jquery" )do %>
					<fieldset>
						<div class="form-group">
							<div class="row">
								<div class="col-lg-8 col-md-8">
									<label>Category Name </label>
								</div>
							</div>
							<div class="row">
								<div class="col-lg-8 col-md-8">
									<%= text_field_tag 'name' , nil , class: "form-control" , :placeholder => "Like : Call , Meeting (etc)..." , required: true %>
								</div>
							</div>
						</div>
					</fieldset>
					<div class="row">
						<div class="col-lg-8 col-md-8">
							<%= submit_tag 'Add Category' , class: "btn btn-primary" %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/project/list_category.html.erb
<%= content_for :header do %>
	Setting - List Cateogry
<% end %>
<%= content_for :Listheader do %>
	<li>Setting</li>
	<li class="active">List Category</li>
<% end %>
<div class="row">
	<div class="col-lg-3">
		<%= render 'all_setting' %>
	</div>
	<div class="col-lg-9">
		<div class="panel panel-flat">
			<div class="panel-heading">
				<span class="my-heading">All Category</span>
					<%= link_to 'Add Category' , add_task_category_path , class: "btn btn-primary pull-right"%>
			</div>
			<div class="panel-body">
				<div class="form-group">
					<div class="table-responsive">
						<table class="table">
							<thead>
								<tr>
									<th>Name</th>
									<th>Edit</th>
									<th>Delete</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>Call</td>
									<td><%= link_to '' , add_task_category_path , class: "glyphicon glyphicon-pencil" %></td>
									<td><%= link_to '' , add_task_category_path , class: "icon-cross" %></td>
								</tr>
								<tr>
									<td>Meeting</td>
									<td><%= link_to '' , add_task_category_path , class: "glyphicon glyphicon-pencil" %></td>
									<td><%= link_to '' , add_task_category_path , class: "icon-cross" %></td>
								</tr>
								<tr>
									<td>Follow-up</td>
									<td><%= link_to '' , add_task_category_path , class: "glyphicon glyphicon-pencil" %></td>
									<td><%= link_to '' , add_task_category_path , class: "icon-cross" %></td>
								</tr>
								<tr>
									<td>E Mail</td>
									<td><%= link_to '' , add_task_category_path , class: "glyphicon glyphicon-pencil" %></td>
									<td><%= link_to '' , add_task_category_path , class: "icon-cross" %></td>
								</tr>
								<tr>
									<td>Send</td>
									<td><%= link_to '' , add_task_category_path , class: "glyphicon glyphicon-pencil" %></td>
									<td><%= link_to '' , add_task_category_path , class: "icon-cross" %></td>
								</tr>
								<tr>
									<td>Milestone</td>
									<td><%= link_to '' , add_task_category_path , class: "glyphicon glyphicon-pencil" %></td>
									<td><%= link_to '' , add_task_category_path , class: "icon-cross" %></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/project/list_notes.html.erb
List_Notes

app/views/project/list_opportunity.html.erb
<%= content_for :header do %>
	List Opportunity
<% end %>
<%= content_for :Listheader do %>
	<li class="active">List Opportunity</li>
<% end %>
<div class="row">
	<div class="panel panel-flat">
		<div class="panel-heading">
			<legend><h6 class="text-semibold">Opportunity
			<%= link_to '' , add_opportunity_path , class: "icon-plus2 pull-right" %></h6></legend>
		</div>

		<div class="panel-body">
			<div class="table-responsive">
				<table class="table datatable-basic">
					<thead class="bg-blue">
						<tr>
							<th>Name</th>
							<th>Expacted Value</th>
							<th>Expacted Colse Date</th>
							<th>Relates to</th>
							<th>Status</th>
							<th></th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><%= link_to 'Business Management System' , opportunity_details_path %></td>
							<td>250000</td>
							<td>10/05/2016</td>
							<td><%= link_to 'Complitech PVT LTD' , nil %></td>
							<td><label class="label bg-blue">Bid</label></td>
							<td><%= link_to '' , nil, class: "icon-pen6" %></td>
							<td></td>
						</tr>
						<tr>
							<td><%= link_to 'Application Development for iOS' , opportunity_details_path %></td>
							<td>175000</td>
							<td>17/04/2016</td>
							<td><%= link_to 'Net Squre Solutions' , nil %></td>
							<td><label class="label bg-orange">Negotiation</label></td>
							<td><%= link_to '' , nil, class: "icon-pen6" %></td>
							<td></td>
						</tr>
						<tr>
							<td><%= link_to 'Stadium' , opportunity_details_path %></td>
							<td>150000</td>
							<td>15/04/2016</td>
							<td><%= link_to 'Complitech PVT LTD' , nil %></td>
							<td><label class="label bg-orange">Negotiation</label></td>
							<td><%= link_to '' , nil, class: "icon-pen6" %></td>
							<td></td>
						</tr>
						<tr>
							<td><%= link_to 'FashionSprout' , opportunity_details_path %></td>
							<td>350000</td>
							<td>20/05/2016</td>
							<td><%= link_to 'indianic' , nil %></td>
							<td><label class="label bg-blue">Bid</label></td>
							<td><%= link_to '' , nil, class: "icon-pen6" %></td>
							<td></td>
						</tr>
						<tr>
							<td><%= link_to 'Select - Home Secutiry' , opportunity_details_path %></td>
							<td>150000</td>
							<td>21/06/2016</td>
							<td><%= link_to 'Net Squre Solutions' , nil %></td>
							<td><label class="label bg-green">New</label></td>
							<td><%= link_to '' , nil, class: "icon-pen6" %></td>
							<td></td>
						</tr>
						<tr>
							<td><%= link_to 'Doctortv' , opportunity_details_path %></td>
							<td>264000</td>
							<td>14/07/2016</td>
							<td><%= link_to 'Complitech PVT LTD' , nil %></td>
							<td><label class="label bg-teal">Analisys</label></td>
							<td><%= link_to '' , nil, class: "icon-pen6" %></td>
							<td></td>
						</tr>
						<tr>
							<td><%= link_to 'Appsylum' , opportunity_details_path %></td>
							<td>148000</td>
							<td>15/07/2016</td>
							<td><%= link_to 'Net Squre Solutions' , nil %></td>
							<td><label class="label bg-violet">Design</label></td>
							<td><%= link_to '' , nil, class: "icon-pen6" %></td>
							<td></td>
						</tr>
						<tr>
							<td><%= link_to 'Rush Hockey' , opportunity_details_path %></td>
							<td>175000</td>
							<td>03/09/2016</td>
							<td><%= link_to 'indianic' , nil %></td>
							<td><label class="label bg-violet">Design</label></td>
							<td><%= link_to '' , nil, class: "icon-pen6" %></td>
							<td></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>		
</div>

<script type="text/javascript">


Morris.Donut({
  element: 'pie-chart',
  data: [
  	{label: "New", value: 2},
    {label: "Bid", value: 15},
    {label: "Analisys", value: 20},
    {label: "Negotiation", value: 35},
    {label: "Won", value: 20},
    {label: "Lose", value: 50}
  ]
});

</script>